import { auth } from "@/src/auth.config";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app"
};

export default async function CheckoutLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.user) {
    // redirect('/auth/login?returnTo=/perfil')
    redirect("/auth/login?redirectTo=/checkout/address");
  }
  return <>{children}</>;
}
