import { auth } from "@/src/auth.config";
import type { Metadata } from "next";
import { redirect } from "next/navigation";



export const metadata: Metadata = {
  title: "Login teslo-shop",
  description: "Generated by create next app",
};

export default async function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  
  if(session?.user){
    redirect('/')
  }

  return (
      <main className="flex justify-center">
        <div className="w-full sm:w-[350px]">
            {children}
        </div>
      </main>
  );
}