import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/config/fonts";
import Provider from "@/components/providers/Provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Provider>
          {children}
       </Provider>
      </body>
    </html>
  );
}
