import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/config/fonts";
import Providers from "@/components/providers/Providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
          {children}
       </Providers>
      </body>
    </html>
  );
}
